# -*- coding: utf-8 -*-
"""
Parâmetros de design alinhados ao GUI_DESIGN_GUIDE.md
e adaptados para o contexto agrícola do Fertisoja.
"""

# Cores primárias
PLANT_COLOR = "#4CAF50"       # Verde para elementos relacionados a plantas
PLANT_HOVER = "#388E3C"
STRAW_COLOR = "#FF9800"       # Laranja para palha
STRAW_HOVER = "#E65100"
SOIL_COLOR = "#795548"        # Marrom para solo
SOIL_HOVER = "#5D4037"

# Cores de ação
PRIMARY_BLUE = "#2196F3"      # Azul principal
PRIMARY_HOVER = "#1976D2"
SUCCESS_GREEN = "#4CAF50"
WARNING_ORANGE = "#FF9800"
DANGER_RED = "#F44336"

# Cores de interface
BACKGROUND_LIGHT = "#f3f5f8"
BACKGROUND_DARK = "#212529"
PANEL_LIGHT = "#ffffff"
PANEL_DARK = "#343a40"
TEXT_PRIMARY = "#1f538d"
TEXT_SECONDARY = "#6c757d"

# Cores de sliders
SLIDER_PLANT = "#4CAF50"
SLIDER_PLANT_BTN = "#2E7D32"
SLIDER_STRAW = "#FF9800"
SLIDER_STRAW_BTN = "#F57C00"

# Cores específicas para Fertisoja
FERTILIZER_COLOR = "#8BC34A"
FERTILIZER_HOVER = "#689F38"
CALC_COLOR = "#FF5722"
CALC_HOVER = "#D84315"
ANALYSIS_COLOR = "#3F51B5"
ANALYSIS_HOVER = "#303F9F"

# Espaçamentos
PADX_STANDARD = 18
PADY_STANDARD = 18
PADX_SMALL = 8
PADY_SMALL = 8
PADX_MICRO = 4

# Tipografia
FONT_SIZE_TITLE = 16
FONT_SIZE_HEADING = 14
FONT_SIZE_BODY = 12
FONT_SIZE_SMALL = 11

# Botões
BUTTON_HEIGHT_PRIMARY = 42
BUTTON_HEIGHT_SECONDARY = 36
BUTTON_HEIGHT_SMALL = 30

# Larguras padrão
BUTTON_WIDTH_PRIMARY = 168
BUTTON_WIDTH_SECONDARY = 132
ENTRY_WIDTH_STANDARD = 140
ENTRY_WIDTH_SMALL = 112

# Cartões e elementos estruturais
CARD_CORNER_RADIUS = 16
CARD_BORDER_WIDTH = 1
CARD_BORDER_COLOR = "#ccd6e4"
CARD_GAP = 10
